# .pre-commit-config.yaml
# Run once:     pre-commit install
# Update hooks: pre-commit autoupdate

repos:
  # --- Core sanity checks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  # --- Formatting / Linting / Types ---
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

###  - repo: https://github.com/pre-commit/mirrors-mypy
###    rev: v1.11.2
###    hooks:
###      - id: mypy
###        additional_dependencies:
###          - types-requests
###          - types-PyYAML

###  - repo: https://github.com/asottile/pyupgrade
###    rev: v3.19.0
###    hooks:
###      - id: pyupgrade
###        args: ["--py311-plus"]

  # --- Spellcheck (avoids typos in code/docs) ---
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=htt,teh,nd
          - --skip=*.lock,*.svg,*.min.js,*.map
        additional_dependencies: [tomli]  # for pyproject parsing on 3.11+
